services:
  db:
    image: postgres:16
    container_name: sittilingi-shg-db
    environment:
      POSTGRES_DB: sittilingi_shg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
